### ISSUE TITLE
Not able to set visibility in Not able to set visibility in FloatingActionButton

### ISSUE THREAD

**Issue by DeveshLoktra** [robertlevonyan/customFloatingActionButton#22]
Not able to set visibility in Not able to set visibility in FloatingActionButton

**Comment by jcampos73** [comment]
Here same problem. Thx

**Comment by djohannot** [comment]
same here, a big problem for us....

**Comment by djohannot** [comment]
As i wanted this show/hide, i have done it my self, here is as video to show you the result (i have set the action on of the the existing floating button).

![demo](https://user-images.githubusercontent.com/35487270/61183550-b921b080-a653-11e9-85e3-660865325925.gif)

For you to know:

- The code on this repo is not the last version of it (missing component declaration, not the correction version number, etc.), i had to do some corrections..... 
- The solution I implemented simply required to call 'showFloatingButton' or 'hideFloatingButton'

If some of you are interested, i will rewrite this small lib in Kotlin, and clean it a bit to let you have this show/hide that i guess you also want :)

I will do it as soon as i have a request (should take a few hours only), otherwise i will keep this change for myself, not because i am selfish but I don't have a lot of time to loose if there is no shared interest.

Wait for you messages!

**Comment by robertlevonyan** [comment]
Thanks sending a feedback. A new version with kotlin and AndroidX support is in development already, that's why I'm not updating this version anymore. So I will push it once I finish. However it's an open source library so you can change and modify it as you wish.

**Comment by djohannot** [comment]
Good news!
please add the two following methods (or if you have an equivalent it's fine) to be able to show/hide the layout content:
`    public void hideFloatingButton(){
        for (int i = 0; i < getChildCount(); i++) {
            View v = getChildAt(i);
            v.setVisibility(View.GONE);
            v.postInvalidate();
        }
        setVisibility(View.GONE);
    }

    public void showFloatingButton(){
        for (int i = 0; i < getChildCount(); i++) {
            View v = getChildAt(i);
            v.setVisibility(View.VISIBLE);
            v.postInvalidate();
        }
        setVisibility(View.VISIBLE);
    }`

**Comment by djohannot** [comment]
and let me know when it's available :)

**Comment by jcampos73** [comment]
I have done more or less the same. Added this methods to FloatingActionButton class:

public class FloatingActionButton extends android.support.v7.widget.AppCompatTextView {
(...)
    public void hide()
    {
        setVisibility(INVISIBLE);
    }

    public void show()
    {
        setVisibility(VISIBLE);
    }
}

**Comment by robertlevonyan** [comment]
In the new version there is both options to hide/show  (with animation) or set visibility manually
